### ISSUE TITLE
Could it produce a normalized histogram?

### ISSUE THREAD

**Issue by Eruias** [medthehatta/roll-histogram#1]
Hello, this request is to ask that of the title. How can I make it so the histogram produced is normalized, or at least to get a txt with the data so I can make it normalized?
Thanks!

**Comment by medthehatta** [comment]
Turns out it's just a matter of passing a parameter `density=1` to the `hist()` function, so I implemented this change in https://github.com/medthehatta/roll-histogram/commit/bc57cdcc703b3076038a833e871ee0ff9bc895f9

Thanks for your interest!
